[project]
name = "clash-deck-builder-docs"
version = "0.1.0"
description = "Documentation for Clash Royale Deck Builder"
requires-python = ">=3.11"

[dependency-groups]
docs = [
    "mkdocs>=1.5.0",
    "mkdocs-material>=9.5.0",
    "pymdown-extensions>=10.0",
]

[tool.uv]
package = false
